config/routes.rb
Issuet::Application.routes.draw do
  root 'dashboard#index'

  devise_for :users
  get 'users/:username', to: 'users#show', as: :user_profile

  resources :projects do
    resources :issues do
      resources :comments
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :issue

  validates :body, presence: true
  validates :user, presence: true
  validates :issue, presence: true
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  before_create :populate_number

  belongs_to :user
  belongs_to :project

  has_many :labels
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :project }
  validates :body, presence: true
  validates :state, inclusion: { in: %w(open closed) }
  validates :user, presence: true
  validates :project, presence: true

  def <<(label)
    labels << label
  end

  def populate_number
    if project
      project.increment!(:issue_sequence)
      self[:number] = project.issue_sequence
    end
  end

  def to_param
    number
  end

  def open
    update_attribute(:state, 'open') unless open?
  end

  def close
    update_attribute(:state, 'closed') if open?
  end

  def open?
    self.state == 'open'
  end
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :project
  belongs_to :issue

  validates :name, presence: true, uniqueness: { scope: :project }
  validates :color,
            presence: true,
            uniqueness: { scope: :project },
            inclusion: { in: %w(default primary success warning danger info) }
  validates :project, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :issues, dependent: :destroy
  has_many :labels, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :user, presence: true

  def <<(issue)
    issues << issue
  end

  def to_param
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  has_many :issues, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :name, presence: true

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login) # rubocop:disable AssignmentInCondition, LineLength
      where(conditions).where([
        'lower(username) = :value OR lower(email) = :value',
        { value: login.downcase }
      ]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # rubocop:disable Blocks, BlockAlignment, LineLength
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
      :username, :email, :name, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(
      :login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(
      :username, :email, :name, :password, :password_confirmation, :current_password) }
    # rubocop:enable Blocks, BlockAlignment, LineLength
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @user = User.find(current_user)
    @project = Project.find_by(name: params[:project_id])
    @issue = @project.issues.find_by(number: params[:issue_id] || params[:id])
    @comment = @issue.comments.new(permit)
    @comment.user = @user

    if @comment.save
      redirect_to project_issue_path(@project.name, @issue.number)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def permit
    comment_params.permit(:body)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    user_signed_in? ? render(:index) : redirect_to(:new_user_session)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :issue_owner?, except: [:index, :new, :create, :show]

  def index
    redirect_to project_path(params[:project_id])
  end

  def new
    @issue = Issue.new
    @project = Project.find_by(name: params[:project_id] || params[:id])
  end

  def create
    @user = User.find(current_user)
    @project = Project.find_by(name: params[:project_id])
    @issue = @project.issues.new(permit)
    @issue.user = @user

    if @issue.save
      redirect_to project_issues_path(@project)
    else
      render 'new'
    end
  end

  def show
    @project = Project.find_by(name: params[:project_id])
    @issue = @project.issues.find_by(number: params[:id])
    @comment = Comment.new
  end

  private

  def issue_owner?
    @issue = Issue.find_by(number: params[:id])
    redirect_to @issue unless @issue.user == current_user
  end

  def issue_params
    params.require(:issue).permit(:title, :body)
  end

  def permit
    issue_params.permit(:title, :body)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project_owner?, except: [:index, :new, :create, :show]

  def index
    redirect_to root_path
  end

  def new
    @project = Project.new
  end

  def create
    @user = User.find(current_user)
    @project = @user.projects.new(permit)

    if @project.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def show
    @project = Project.find_by(name: params[:id])
    @issues = @project.issues
    @owner = User.find(@project.user_id)
  end

  def edit
    @project = Project.find_by(name: params[:id])
  end

  def update
    @project = Project.find_by(name: params[:id])

    if @project.update(permit)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    Project.find_by(name: params[:id]).destroy
    redirect_to root_path
  end

  private

  def project_owner?
    @project = Project.find_by(name: params[:id])
    redirect_to @project unless @project.user == current_user
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def permit
    project_params.permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def to_markdown(content)
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML.new(filter_html: true),
      no_intra_emphasis: true,
      tables: true,
      strikethrough: true,
      space_after_headers: true)
    markdown.render(content).html_safe
  end

  def full_title(page_title)
    page_title.empty? ? 'Issuet' : page_title
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map do |msg|
      content_tag(:li, msg)
    end.join
    sentence = I18n.t(
      'errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = generate_html(sentence, messages)

    html.html_safe
  end

  def generate_html(sentence, messages)
    <<-HTML
    <div class='alert alert-warning'>
      <h4>#{sentence}</h4>
      <ul>
        #{messages}
      </ul>
    </div>
    HTML
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.haml
= provide :title, 'Dashboard'

%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.haml

app/views/issues/_comment_errors.html.haml
- if @comment.errors.any?
  .alert.alert-danger.alert-dismissable
    %button.close{'type' => 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'} &times;
    %strong
      = pluralize @comment.errors.count, 'error'
      prohibited this comment from being saved:
    %ul
      - @comment.errors.full_messages.each do |msg|
        %li= msg

app/views/issues/_errors.html.haml
- if @issue.errors.any?
  .alert.alert-danger.alert-dismissable
    %button.close{'type' => 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'} &times;
    %strong
      = pluralize @issue.errors.count, 'error'
      prohibited this issue from being saved:
    %ul
      - @issue.errors.full_messages.each do |msg|
        %li= msg

app/views/issues/new.html.haml
= provide :title, "New issue · #{@project.user.username}/#{@project.name}"

= render 'shared/project_header'

.row
  .col-md-4
  .col-md-4
    .panel.panel-default
      .panel-heading.text-center
        %h2.panel-title Create a new issue
      .panel-body
        = render 'errors'
        = form_for @issue, url: project_issues_path, method: :post, class: 'input-group input-group-lg' do |f|
          = f.text_field :title, placeholder: 'Issue title', required: 'true', autofocus: true, class: 'form-control'
          %br
          = f.text_area :body, placeholder: 'Issue body', required: 'true', class: 'form-control'
          %br
          = f.submit 'Create issue', class: 'btn btn-success btn-block'
  .col-md-4

app/views/issues/show.html.haml
= render 'shared/project_header'

.row
  .col-md-2
    - if @issue.state == 'open'
      %button.btn.btn-lg.btn-block.btn-success.disabled= @issue.state
    - else
      %button.btn.btn-lg.btn-block.btn-danger.disabled= @issue.state
    %hr
    - if @issue.labels.any?
      - @issue.labels.each do |label|
        %button.btn.btn-xs.btn-block.disabled{'class' => "btn-#{label.color}"}= label.name
    - else
      %h6.text-center No labels to show.
  .col-md-10
    .jumbotron
      %h1= @issue.title
      %p= to_markdown(@issue.body)
    - if @issue.comments.any?
      - @issue.comments.each do |comment|
        .media
          %a.pull-left{'href' => user_profile_path(comment.user.username)}
            = gravatar_image_tag comment.user.email, class: 'media-object', gravatar: { size: 64 }
          .media-body
            %h6.media-heading
              = link_to comment.user.username, user_profile_path(comment.user.username)
              commented
              = time_ago_in_words(comment.created_at)
              ago
            = comment.body
        %hr
    - else
      %h6.text-center No comments to show.
    .row
      = render 'comment_errors'
      = form_for @comment, url: project_issue_comments_path(@project.name, @issue.number), method: :post, class: 'input-group input-group-lg' do |f|
        .col-md-9= f.text_area :body, placeholder: 'Leave a comment', required: 'true', autofocus: true, style: 'resize:vertical', class: 'form-control'
        .col-md-3= f.submit 'Create comment', class: 'btn btn-success btn-block'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-static-top{'role' => 'navigation'}
      .container
        .navbar-header
          %button.navbar-toggle{'type' => 'button', 'data-toggle' => 'collapse', 'data-target' => '#main-navbar'}
            %span.sr-only Toggle Navigation
            - 3.times do
              %span.icon-bar
          %a.navbar-brand{'href' => '/'} Issuet
        .collapse.navbar-collapse#main-navbar
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to 'Create a new project', new_project_path
              %li.dropdown
                %a.dropdown-toggle{'href' => '#', 'data-toggle' => 'dropdown'}
                  = gravatar_image_tag current_user.email, alt: '', style: 'margin-right: 5px; margin-bottom: 1px;', gravatar: { size: 20 }
                  = current_user.username
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'My profile', user_profile_path(current_user.username)
                  %li= link_to 'Account settings', edit_user_registration_path
                  %li.divider
                  %li= link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              %li= link_to 'Sign in', new_user_session_path
    .container
      - if notice
        .alert.alert-success.alert-dissmissable
          %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} &times;
          = notice
      - if alert
        .alert.alert-warning.alert-dissmissable
          %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} &times;
          = alert
      = yield
  .container
    %br
    .well.well-sm.text-center
      Copyright &copy; Rafal Chmiel & Co. &mdash; An
      %a{'href' => 'https://github.com/rafalchmiel/issuet'} open source
      project.
  = javascript_include_tag '//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js'

app/views/projects/_errors.html.haml
- if @project.errors.any?
  .alert.alert-danger.alert-dismissable
    %button.close{'type' => 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'} &times;
    %strong
      = pluralize @project.errors.count, 'error'
      prohibited this project from being saved:
    %ul
      - @project.errors.full_messages.each do |msg|
        %li= msg

app/views/projects/edit.html.haml
= provide :title, "Project settings · #{@project.user.username}/#{@project.name}"

= render 'shared/project_header'

.row
  .col-md-4
  .col-md-4
    .panel.panel-default
      .panel-heading.text-center
        %h2.panel-title
          Edit project settings
      .panel-body
        = render 'errors'
        = form_for @project, url: project_path, method: :patch, class: 'input-group input-group-lg' do |f|
          = f.text_field :name, placeholder: 'Project name', required: 'true', autofocus: true, class: 'form-control'
          %br
          = f.text_field :description, placeholder: 'Description (optional)', class: 'form-control'
          %br
          = f.submit 'Save changes', class: 'btn btn-default btn-block'
      .panel-footer
        = button_to 'Delete project', project_path, data: { confirm: 'Are you sure you want to delete this project?' }, method: :delete, class: 'btn btn-xs btn-warning btn-block'
  .col-md-4

app/views/projects/new.html.haml
= provide :title, 'Create a new project'

.row
  .col-md-4
  .col-md-4
    .panel.panel-default
      .panel-heading.text-center
        %h2.panel-title Create a new project
      .panel-body
        = render 'errors'
        = form_for @project, url: projects_path, method: :post, class: 'input-group input-group-lg' do |f|
          = f.text_field :name, placeholder: 'Project name', required: 'true', autofocus: true, class: 'form-control'
          %br
          = f.text_field :description, placeholder: 'Description (optional)', class: 'form-control'
          %br
          = f.submit 'Create project', class: 'btn btn-success btn-block'
  .col-md-4

app/views/projects/show.html.haml
= provide :title, "Issues · #{@project.user.username}/#{@project.name}"

= render 'shared/project_header'

.row
  .col-md-2
    %ul.nav.nav-pills.nav-stacked
      - open_count = @issues.where(state: 'open').count
      - closed_count = @issues.count - open_count
      - if !params[:state] || (params[:state] == 'open')
        %li.active= link_to "#{open_count} open"
      - else
        %li= link_to "#{open_count} open", '?state=open'
      - if params[:state] == 'closed'
        %li.active= link_to "#{closed_count} closed"
      - else
        %li= link_to "#{closed_count} closed", '?state=closed'
  .col-md-10
    .list-group
      - if @issues.any?
        - @issues.where(state: params[:state] || 'open').each do |issue|
          %a.list-group-item{'href' => project_issue_path(@project.name, issue.number)}
            %span.badge= "##{issue.number}"
            %span.badge= issue.state
            - if issue.comments.any?
              %span.badge
                %span.glyphicon.glyphicon-comment
                = issue.comments.count
            %h4.list-group-item-heading
              = issue.title
            %p.list-group-item-text.text-muted
              Opened by
              = issue.user.username
              = time_ago_in_words(issue.created_at)
              ago
              - if issue.labels.any?
                - issue.labels.each do |label|
                  %span.label{'class' => "label-#{label.color}"}= label.name
      - else
        .list-group-item.text-center
          No issues to show.
          = link_to 'Create a new issue.', new_project_issue_path(@project)

app/views/shared/_project_header.html.haml
.row
  .col-md-12
    %h1
      - owner_username = @project.user.username
      - current_uri = request.env['PATH_INFO']

      = link_to owner_username, user_profile_path(owner_username)
      \/
      = link_to @project.name, project_path(@project)
      - unless @project.description.blank?
        %small= @project.description
    %br
    %ul.nav.nav-pills.nav-justified
      - if current_uri == project_path(@project)
        %li.active= link_to 'Issues', ''
      - else
        %li= link_to 'Issues', project_path(@project)
      - if current_uri == new_project_issue_path(@project)
        %li.active= link_to 'New issue', ''
      - else
        %li= link_to 'New issue', new_project_issue_path(@project)
      - if @project.user_id == current_user.id
        - if current_uri == edit_project_path(@project)
          %li.active= link_to 'Project settings', ''
        - else
          %li= link_to 'Project settings', edit_project_path(@project)
%br
%br

app/views/users/show.html.haml
= provide :title, "#{@user.username} (#{@user.name})"

.row
  .col-md-3
    = gravatar_image_tag @user.email, alt: 'Change your avatar at gravatar.com', class: 'gravatar', title: 'Change your avatar at gravatar.com', gravatar: { size: 512 }
    %h2
      = @user.name
      %br
      %small= @user.username
    %hr
    %h5
      %span.glyphicon.glyphicon-envelope
      = link_to @user.email, "mailto: #{@user.email}"
    %h5
      %span.glyphicon.glyphicon-book
      Owns
      = pluralize(@user.projects.count, 'project')
    %h5
      %span.glyphicon.glyphicon-flag
      Created
      = pluralize(@user.issues.count, 'issue')
    %h5
      %span.glyphicon.glyphicon-comment
      Wrote
      = pluralize(@user.comments.count, 'comment')
    %h5
      %span.glyphicon.glyphicon-time
      Joined on
      = @user.created_at.strftime('%b %e, %Y')
  .col-md-5
    %br
    .panel.panel-default
      .panel-heading
        %h2.panel-title
          Projects
          %small by
          %small= @user.username
      %ul.list-group
        - if @user.projects.any?
          - default_project_limit = 6
          - @user.projects.order('updated_at DESC').limit(params[:p] || default_project_limit).each do |project|
            %a.list-group-item{'href' => project_path(project)}
              %span.badge= "#{project.issues.count} issues"
              %h4.list-group-item-heading{'title' => "Last updated #{time_ago_in_words(project.updated_at)} ago"}
                = project.name
                - unless project.description.blank?
                  %small= project.description
          - if (@user.projects.count > default_project_limit) && (params[:p].to_i < @user.projects.count)
            %a.list-group-item{'href' => user_profile_path(@user.username, p: @user.projects.count)}
              %h4.list-group-item-heading.text-center Show all projects
        - else
          .panel-body
            %br
            %p.text-center No projects to show.

  / .col-md-4
  /   .panel.panel-default
  /     .panel-heading
  /       %h2.panel-title
  /         Issues
  /         %small by
  /         %small= @user.username
  /     %ul.list-group
  /       - if @user.issues.blank?
  /         .panel-body
  /           %br
  /           %p.text-center No issues to show.
  /       - else
  /         - @user.issues.order('created_at DESC').each do |issue|
  /           %a.list-group-item{'href' => issue_path(issue)}
  /             %h4.list-group-item-heading= issue.title